var tree = [["AuthBucket",,"",
                [["Push",,"",
                [["Controller","AuthBucket\/Push\/Controller.html","",
                [["ApplicationController","AuthBucket\/Push\/Controller\/ApplicationController.html","",
                [        ]],["DeviceController","AuthBucket\/Push\/Controller\/DeviceController.html","",
                [        ]],["MessageController","AuthBucket\/Push\/Controller\/MessageController.html","",
                [        ]],["PushController","AuthBucket\/Push\/Controller\/PushController.html","",
                [        ]],["VariantController","AuthBucket\/Push\/Controller\/VariantController.html","",
                [        ]]        ]],["EventListener","AuthBucket\/Push\/EventListener.html","",
                [["ExceptionListener","AuthBucket\/Push\/EventListener\/ExceptionListener.html","",
                [        ]]        ]],["Exception","AuthBucket\/Push\/Exception.html","",
                [["AccessDeniedException","AuthBucket\/Push\/Exception\/AccessDeniedException.html"," < LogicException",
                [        ]],["ExceptionInterface","AuthBucket\/Push\/Exception\/ExceptionInterface.html","",
                [        ]],["InvalidRequestException","AuthBucket\/Push\/Exception\/InvalidRequestException.html"," < InvalidArgumentException",
                [        ]],["ServerErrorException","AuthBucket\/Push\/Exception\/ServerErrorException.html"," < LogicException",
                [        ]],["TemporarilyUnavailableException","AuthBucket\/Push\/Exception\/TemporarilyUnavailableException.html"," < LogicException",
                [        ]],["UnsupportedVariantTypeException","AuthBucket\/Push\/Exception\/UnsupportedVariantTypeException.html"," < InvalidArgumentException",
                [        ]]        ]],["Model","AuthBucket\/Push\/Model.html","",
                [["ApplicationInterface","AuthBucket\/Push\/Model\/ApplicationInterface.html","",
                [        ]],["ApplicationManagerInterface","AuthBucket\/Push\/Model\/ApplicationManagerInterface.html","",
                [        ]],["DeviceInterface","AuthBucket\/Push\/Model\/DeviceInterface.html","",
                [        ]],["DeviceManagerInterface","AuthBucket\/Push\/Model\/DeviceManagerInterface.html","",
                [        ]],["MessageInterface","AuthBucket\/Push\/Model\/MessageInterface.html","",
                [        ]],["MessageManagerInterface","AuthBucket\/Push\/Model\/MessageManagerInterface.html","",
                [        ]],["ModelInterface","AuthBucket\/Push\/Model\/ModelInterface.html","",
                [        ]],["ModelManagerFactoryInterface","AuthBucket\/Push\/Model\/ModelManagerFactoryInterface.html","",
                [        ]],["ModelManagerInterface","AuthBucket\/Push\/Model\/ModelManagerInterface.html","",
                [        ]],["VariantInterface","AuthBucket\/Push\/Model\/VariantInterface.html","",
                [        ]],["VariantManagerInterface","AuthBucket\/Push\/Model\/VariantManagerInterface.html","",
                [        ]]        ]],["Provider","AuthBucket\/Push\/Provider.html","",
                [["AuthBucketPushServiceProvider","AuthBucket\/Push\/Provider\/AuthBucketPushServiceProvider.html","",
                [        ]]        ]],["Validator",,"",
                [["Constraints","AuthBucket\/Push\/Validator\/Constraints.html","",
                [["ClientId","AuthBucket\/Push\/Validator\/Constraints\/ClientId.html"," < Regex",
                [        ]],["ClientIdValidator","AuthBucket\/Push\/Validator\/Constraints\/ClientIdValidator.html"," < RegexValidator",
                [        ]],["ClientSecret","AuthBucket\/Push\/Validator\/Constraints\/ClientSecret.html"," < Regex",
                [        ]],["ClientSecretValidator","AuthBucket\/Push\/Validator\/Constraints\/ClientSecretValidator.html"," < RegexValidator",
                [        ]],["DeviceToken","AuthBucket\/Push\/Validator\/Constraints\/DeviceToken.html"," < Regex",
                [        ]],["DeviceTokenValidator","AuthBucket\/Push\/Validator\/Constraints\/DeviceTokenValidator.html"," < RegexValidator",
                [        ]],["Error","AuthBucket\/Push\/Validator\/Constraints\/Error.html"," < Regex",
                [        ]],["ErrorDescription","AuthBucket\/Push\/Validator\/Constraints\/ErrorDescription.html"," < Regex",
                [        ]],["ErrorDescriptionValidator","AuthBucket\/Push\/Validator\/Constraints\/ErrorDescriptionValidator.html"," < RegexValidator",
                [        ]],["ErrorUri","AuthBucket\/Push\/Validator\/Constraints\/ErrorUri.html"," < Url",
                [        ]],["ErrorUriValidator","AuthBucket\/Push\/Validator\/Constraints\/ErrorUriValidator.html"," < UrlValidator",
                [        ]],["ErrorValidator","AuthBucket\/Push\/Validator\/Constraints\/ErrorValidator.html"," < RegexValidator",
                [        ]],["ExpiresIn","AuthBucket\/Push\/Validator\/Constraints\/ExpiresIn.html"," < Regex",
                [        ]],["ExpiresInValidator","AuthBucket\/Push\/Validator\/Constraints\/ExpiresInValidator.html"," < RegexValidator",
                [        ]],["Password","AuthBucket\/Push\/Validator\/Constraints\/Password.html"," < Regex",
                [        ]],["PasswordValidator","AuthBucket\/Push\/Validator\/Constraints\/PasswordValidator.html"," < RegexValidator",
                [        ]],["State","AuthBucket\/Push\/Validator\/Constraints\/State.html"," < Regex",
                [        ]],["StateValidator","AuthBucket\/Push\/Validator\/Constraints\/StateValidator.html"," < RegexValidator",
                [        ]],["Username","AuthBucket\/Push\/Validator\/Constraints\/Username.html"," < Regex",
                [        ]],["UsernameValidator","AuthBucket\/Push\/Validator\/Constraints\/UsernameValidator.html"," < RegexValidator",
                [        ]],["VariantType","AuthBucket\/Push\/Validator\/Constraints\/VariantType.html"," < Regex",
                [        ]],["VariantTypeValidator","AuthBucket\/Push\/Validator\/Constraints\/VariantTypeValidator.html"," < RegexValidator",
                [        ]]        ]]        ]],["VariantType","AuthBucket\/Push\/VariantType.html","",
                [["AbstractVariantTypeHandler","AuthBucket\/Push\/VariantType\/AbstractVariantTypeHandler.html","",
                [        ]],["ApnsVariantTypeHandler","AuthBucket\/Push\/VariantType\/ApnsVariantTypeHandler.html"," < AbstractVariantTypeHandler",
                [        ]],["GcmVariantTypeHandler","AuthBucket\/Push\/VariantType\/GcmVariantTypeHandler.html"," < AbstractVariantTypeHandler",
                [        ]],["VariantTypeHandlerFactory","AuthBucket\/Push\/VariantType\/VariantTypeHandlerFactory.html","",
                [        ]],["VariantTypeHandlerFactoryInterface","AuthBucket\/Push\/VariantType\/VariantTypeHandlerFactoryInterface.html","",
                [        ]],["VariantTypeHandlerInterface","AuthBucket\/Push\/VariantType\/VariantTypeHandlerInterface.html","",
                [        ]]        ]]        ]]        ]]        ]

