---

sudo: false

dist: trusty

language: php

before_install:
  - composer self-update
  - composer global require satooshi/php-coveralls:@stable
  - export PATH="$PATH:$HOME/.composer/vendor/bin"

install:
  - sh -c "if [ '$SYMFONY_DEPS_VERSION' = '2.7' ]; then sed -i 's/~2.7/2.7.*@dev/g' composer.json; composer update; fi"
  - sh -c "if [ '$SYMFONY_DEPS_VERSION' = '2.8' ]; then sed -i 's/~2.7/2.8.*@dev/g' composer.json; composer update; fi"
  - composer install --prefer-source

before_script:
  - mkdir -p build/logs
  - rm -rf app/cache/*/*

script:
  - composer phpunit

after_script:
  - composer coveralls

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 5.6
      env: SYMFONY_DEPS_VERSION=2.7
    - php: 5.6
      env: SYMFONY_DEPS_VERSION=2.8
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: 7.0
    - php: hhvm
