language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install --dev --prefer-source

script:
  - vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover ./build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
