language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update

install:
  - composer install --prefer-source

before_script:
  - mkdir -p build/logs
  - rm -rf app/cache/*/*

script:
  - composer phpunit

after_script:
  - composer coveralls

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
